services:
  # --- INFRASTRUCTURE (Tier 0) ---
  
  redis:
    image: redis:7-alpine
    container_name: tinyurl_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - tinyurl_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db_master:
    image: postgres:15-alpine
    container_name: tinyurl_postgres
    env_file:
      - .env
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - tinyurl_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- KAFKA INFRASTRUCTURE (For Analytics) ---

  kafka:
    image: 'apache/kafka-native:latest'
    container_name: tinyurl_kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
    networks: [tinyurl_net]


  # --- SERVICES (Tier 1 & 2) ---

  kgs:
    build:
      context: ./service_kgs
    container_name: tinyurl_kgs
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db_master:
        condition: service_healthy
    networks:
      - tinyurl_net

  shortener:
    build:
      context: ./service_shortener
    container_name: tinyurl_shortener
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db_master:
        condition: service_healthy
      kgs:
        condition: service_started
    networks:
      - tinyurl_net

  redirector:
    build:
      context: ./service_redirector
    container_name: tinyurl_redirector
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      redis:
        condition: service_healthy
      db_master:
        condition: service_healthy
      kafka: # Redirector (Producer) depends on Kafka being ready
        condition: service_started
      shortener:
        condition: service_started
    networks:
      - tinyurl_net

  # 4. Analytics Worker (The Kafka Consumer)
  analytics_worker:
    build:
      context: ./service_analytics
    container_name: tinyurl_analytics_worker
    env_file:
      - .env
    # Worker needs Kafka to read from and DB to write to
    depends_on:
      kafka:
        condition: service_started
      db_master:
        condition: service_healthy
    networks:
      - tinyurl_net

networks:
  tinyurl_net:
    driver: bridge